version: "3.3"
services:
  xroad-primary-security-server:
    build:
      context: security-server-nodes
      dockerfile: Dockerfile.primary-node
    container_name: xroad-primary-security-server
    environment:
      - XROAD_LOG_LEVEL=DEBUG
      - XROAD_DB_HOST=xroad-db
      - XROAD_DB_PORT=5432
      - XROAD_DB_PWD=xroad
      - SSH_PUBLIC_KEY_BASE64=${ssh_public_key}
    depends_on:
      - xroad-db

  xroad-secondary-security-server:
    build:
      context: security-server-nodes
      dockerfile: Dockerfile.secondary-node
    container_name: xroad-secondary-security-server
    ports:
      - "14000:4000"
      - "15588:5588"
      - "18443:8443"
      - "5500:5500"
      - "5577:5577"
    environment:
      - XROAD_LOG_LEVEL=DEBUG
      - XROAD_DB_HOST=xroad-db
      - XROAD_DB_PORT=5432
      - XROAD_DB_PWD=xroad
      - SSH_PRIVATE_KEY_BASE64=${ssh_private_key}
      - XROAD_PRIMARY_DNS=xroad-primary-security-server
    depends_on:
      - xroad-primary-security-server

  xroad-db:
    image: postgres:12
    container_name: xroad-db
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=xroad
