FROM niis/xroad-security-server-sidecar:7.8.2-primary-fi@sha256:79123ce502af72e654e89ead67d5f43ac7f0cb0b817287f60eaf2c8393179cb3

COPY ./local.ini /root/local.ini

CMD mkdir /etc/.ssh && \
    chmod 755 /etc/.ssh && \
    echo -n ${SSH_PUBLIC_KEY_BASE64} | base64 --decode > /etc/.ssh/id_rsa.pub && \
    chmod 644 /etc/.ssh/id_rsa.pub && \
    cp /root/local.ini /etc/xroad/conf.d/local.ini && \
    /root/entrypoint.sh
