FROM niis/xroad-security-server-sidecar:7.5.1-secondary-fi@sha256:b69319cd59a80eae3e4061ffc2dfa88feb7ab35dd90503fe9ecf184738d16117

CMD mkdir /etc/.ssh && \
    chmod 755 /etc/.ssh && \
    echo -n ${SSH_PRIVATE_KEY_BASE64} | base64 --decode > /etc/.ssh/id_rsa && \
    chmod 644 /etc/.ssh/id_rsa && \
    /root/entrypoint.sh
