FROM niis/xroad-security-server-sidecar:7.8.2-primary-fi@sha256:979de6ffe2e710a7e364637b0621f0e4586df9c2f24ce2ea08092d512dfb1ee7

COPY ./local.ini /root/local.ini

CMD mkdir /etc/.ssh && \
    chmod 755 /etc/.ssh && \
    echo -n ${SSH_PUBLIC_KEY_BASE64} | base64 --decode > /etc/.ssh/id_rsa.pub && \
    chmod 644 /etc/.ssh/id_rsa.pub && \
    cp /root/local.ini /etc/xroad/conf.d/local.ini && \
    /root/entrypoint.sh
