FROM niis/xroad-security-server-sidecar:7.8.1-secondary-fi@sha256:17a22ceaebd72d554fff866d2bd90fda8dd858a06f7620c2b1ef89ea6f1355a5

CMD mkdir /etc/.ssh && \
    chmod 755 /etc/.ssh && \
    echo -n ${SSH_PRIVATE_KEY_BASE64} | base64 --decode > /etc/.ssh/id_rsa && \
    chmod 644 /etc/.ssh/id_rsa && \
    /root/entrypoint.sh
