FROM niis/xroad-security-server-sidecar:7.8.0-primary-fi@sha256:52a75ae2299007b2883c4fd8fe3d2abc37aed73b3f88ac2ab63b99b8b0086a8d

COPY ./local.ini /root/local.ini

CMD mkdir /etc/.ssh && \
    chmod 755 /etc/.ssh && \
    echo -n ${SSH_PUBLIC_KEY_BASE64} | base64 --decode > /etc/.ssh/id_rsa.pub && \
    chmod 644 /etc/.ssh/id_rsa.pub && \
    cp /root/local.ini /etc/xroad/conf.d/local.ini && \
    /root/entrypoint.sh
